### ISSUE TITLE
Feature request : single image mode

### ISSUE THREAD

**Issue by mhashim6** [Thunder07/-XPOSED-MOD-Zeus-Contextual-Expanded-Status-Header#4]
A mode that allows the user to set an image that doesn't change according to the time.

**Comment by Zer0xFF** [comment]
Hi, thanks for the suggestion.

however, such feature will defeat the whole point of this module being "contextual".
as such I'm unlikely to spend time to get it to work, but I'm willing to merge such feature if you do get around adding it yourself.

but if you want a hacky way around it, you've 2 options, (1) just add the same image to all 4 time slots, or (2) add this code to the constructor and remove all references to 'updateBG()'
```
		File dir = new File(Environment.getExternalStorageDirectory().getPath() + "/ZCESH_BG/MORNING_BG");

		if(dir != null && dir.exists() && dir.isDirectory())
		{
			for(File childfile : dir.listFiles())
			{
				if(childfile.isFile())
				{
					if(childfile.getName().toLowerCase().contains(".jpg") || childfile.getName().toLowerCase().contains(".png"))
					{
						Bitmap img = BitmapFactory.decodeFile(childfile.getAbsolutePath());
						setImageBitmap(img);
						break;
					}
				}
			}
```
this will force the status bar into using the 1st Morning picture by the user.

**Comment by Zer0xFF** [comment]
Please feel free to add any further comments, but I'll be closing the issue.

**Comment by mhashim6** [comment]
yes, I've been using the first work around for a while now :)
I guess I will have a go with the implementation myself, when I have the time, Thanks.

Edit: I created a PR.
